// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xgmecfweeyaovfllvaze.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhnbWVjZndlZXlhb3ZmbGx2YXplIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA1MDAzMTUsImV4cCI6MjA2NjA3NjMxNX0.PYEpvwzuXxS-hBJBeLYynJJrPUw_eD84qqgrRvqvJb4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);